version: '1'
services:
    phpfpm:
        container_name: phpfpm
        image: mehrezsamir/php-fpm
        ports:
            - 3000:3000
        volumes:
            - ./:/var/www
        command: php -S="0.0.0.0:3000" -t="/var/www"